import os
import sqlite3
import pandas as pd
import streamlit as st
import plotly.express as px

from analysis import (
    get_frequency_table,
    get_melanoma_miraclib_frequencies,
    get_baseline_subset_analysis,
    run_statistical_comparison,
    CELL_COLS,
)

# ── Page config ───────────────────────────────────────────────────────────────
st.set_page_config(
    page_title="Miraclib Clinical Trials",
    layout="wide",
    initial_sidebar_state="collapsed",
)

st.markdown(
    """
    <style>
    [data-testid="stMetricLabel"] {
        font-size: 0.72rem;
        text-transform: uppercase;
        letter-spacing: 0.07em;
        color: #888;
    }
    [data-testid="stMetricValue"] { font-size: 1.5rem; font-weight: 600; }
    .block-container { padding-top: 1.8rem; padding-bottom: 2rem; }

    </style>
    """,
    unsafe_allow_html=True,
)

CHART_TEMPLATE = "plotly_white"
RESPONSE_COLORS = {"yes": "#2B5EA7", "no": "#ADADAD"}
BAR_SEQUENCE = ["#2B5EA7", "#5C8DD6", "#ADADAD", "#D4D4D4"]

# ── Header ────────────────────────────────────────────────────────────────────
st.markdown("## Miraclib Clinical Trials")

db_col, _ = st.columns([2, 3])
with db_col:
    db_path = st.text_input(
        "Database path",
        value="clinical_trial.db",
        help="Path to the SQLite database file. Run `python load_data.py` to create it. Accepts a relative or absolute path to a `.db` SQLite file generated by `load_data.py`.",
        placeholder="e.g. clinical_trial.db",
    )

st.session_state["db_path"] = db_path

if not os.path.exists(db_path):
    st.warning(f"Database file '{db_path}' not found. Run `python load_data.py` to create it.")
    st.stop()

st.divider()

# ── Cached queries ────────────────────────────────────────────────────────────
@st.cache_data
def cached_get_frequency_table(db_path):
    return get_frequency_table(db_path)


@st.cache_data
def cached_get_melanoma_miraclib_frequencies(db_path):
    return get_melanoma_miraclib_frequencies(db_path)


@st.cache_data
def cached_run_statistical_comparison(db_path):
    freq_df = cached_get_melanoma_miraclib_frequencies(db_path)
    return run_statistical_comparison(freq_df)


@st.cache_data
def cached_get_baseline_subset_analysis(db_path):
    return get_baseline_subset_analysis(db_path)


@st.cache_data
def get_subject_count(db_path):
    conn = sqlite3.connect(db_path)
    n = conn.execute("SELECT COUNT(DISTINCT subject_id) FROM subjects").fetchone()[0]
    conn.close()
    return n


# ── Tabs ──────────────────────────────────────────────────────────────────────
tabs = st.tabs(["Data Overview", "Statistical Analysis", "Subset Analysis", "Schema"])

# ── Tab 0: Data Overview ──────────────────────────────────────────────────────
with tabs[0]:
    freq_df = cached_get_frequency_table(db_path)
    total_samples = freq_df["sample"].nunique()
    total_subjects = get_subject_count(db_path)

    col1, col2, col3 = st.columns([1, 1, 3])
    col1.metric("Samples", total_samples)
    col2.metric("Subjects", total_subjects)
    with col3:
        st.caption("Cell populations tracked")
        st.markdown(" &nbsp; ".join(f"`{c}`" for c in CELL_COLS), unsafe_allow_html=True)

    st.divider()
    st.dataframe(freq_df, use_container_width=True)

    st.download_button(
        label="Export CSV",
        data=freq_df.to_csv(index=False),
        file_name="frequency_table.csv",
        mime="text/csv",
    )

# ── Tab 1: Statistical Analysis ───────────────────────────────────────────────
with tabs[1]:
    st.caption(
        "Melanoma patients treated with miraclib (PBMC samples only). "
        "Responders vs. non-responders compared via Mann-Whitney U test. "
        "Significance threshold: p < 0.05."
    )

    melanoma_freq_df = cached_get_melanoma_miraclib_frequencies(db_path)
    stats_df = cached_run_statistical_comparison(db_path)

    display_df = stats_df[
        ["population", "responder_median", "non_responder_median", "u_statistic", "p_value", "significant"]
    ].copy()
    display_df["significant"] = display_df["significant"].map({True: "Yes", False: "No"})
    display_df = display_df.rename(columns={"significant": "Significant"})
    st.dataframe(display_df, use_container_width=True, hide_index=True)

    st.divider()

    populations = melanoma_freq_df["population"].unique().tolist()
    for i in range(0, len(populations), 2):
        cols = st.columns(2)
        for j, col in enumerate(cols):
            if i + j >= len(populations):
                break
            pop = populations[i + j]
            pop_df = melanoma_freq_df[melanoma_freq_df["population"] == pop]
            fig = px.box(
                pop_df,
                x="response",
                y="percentage",
                color="response",
                points="all",
                title=pop,
                color_discrete_map=RESPONSE_COLORS,
                template=CHART_TEMPLATE,
            )
            fig.update_layout(
                showlegend=False,
                margin=dict(t=40, b=20, l=20, r=20),
                title_font_size=16,
                title_font_color="white",
            )
            col.plotly_chart(fig, use_container_width=True)

# ── Tab 2: Subset Analysis ────────────────────────────────────────────────────
with tabs[2]:
    st.subheader("Baseline Analysis")
    st.caption("Melanoma patients receiving miraclib at baseline (day 0), PBMC samples only.")

    subset = cached_get_baseline_subset_analysis(db_path)
    baseline_samples = subset["baseline_samples"]
    samples_by_project = subset["samples_by_project"]
    subjects_by_response = subset["subjects_by_response"]
    subjects_by_sex = subset["subjects_by_sex"]

    responders = subjects_by_response.loc[subjects_by_response["response"] == "yes", "subject_count"].sum()
    non_responders = subjects_by_response.loc[subjects_by_response["response"] == "no", "subject_count"].sum()

    m1, m2, m3 = st.columns(3)
    m1.metric("Baseline Samples", len(baseline_samples))
    m2.metric("Responders", int(responders))
    m3.metric("Non-Responders", int(non_responders))

    st.divider()

    c1, c2, c3 = st.columns(3)

    with c1:
        st.markdown("**Samples by Project**")
        st.dataframe(samples_by_project, use_container_width=True, hide_index=True)
        fig = px.bar(
            samples_by_project,
            x="project",
            y="sample_count",
            template=CHART_TEMPLATE,
            color_discrete_sequence=BAR_SEQUENCE,
        )
        fig.update_layout(showlegend=False, margin=dict(t=10, b=20, l=20, r=20))
        st.plotly_chart(fig, use_container_width=True)

    with c2:
        st.markdown("**Subjects by Response**")
        st.dataframe(subjects_by_response, use_container_width=True, hide_index=True)
        fig = px.bar(
            subjects_by_response,
            x="response",
            y="subject_count",
            color="response",
            template=CHART_TEMPLATE,
            color_discrete_map=RESPONSE_COLORS,
        )
        fig.update_layout(showlegend=False, margin=dict(t=10, b=20, l=20, r=20))
        st.plotly_chart(fig, use_container_width=True)

    with c3:
        st.markdown("**Subjects by Sex**")
        st.dataframe(subjects_by_sex, use_container_width=True, hide_index=True)
        fig = px.bar(
            subjects_by_sex,
            x="sex",
            y="subject_count",
            template=CHART_TEMPLATE,
            color_discrete_sequence=BAR_SEQUENCE,
        )
        fig.update_layout(showlegend=False, margin=dict(t=10, b=20, l=20, r=20))
        st.plotly_chart(fig, use_container_width=True)

# ── Tab 3: Schema ─────────────────────────────────────────────────────────────
with tabs[3]:
    try:
        conn = sqlite3.connect(db_path)

        subject_count = conn.execute("SELECT COUNT(*) FROM subjects").fetchone()[0]
        sample_count = conn.execute("SELECT COUNT(*) FROM samples").fetchone()[0]

        mc1, mc2 = st.columns(2)
        mc1.metric("Subjects", subject_count)
        mc2.metric("Samples", sample_count)

        st.divider()

        st.markdown("**subjects**")
        subjects_info = pd.read_sql_query("PRAGMA table_info(subjects)", conn)
        st.dataframe(subjects_info, use_container_width=True, hide_index=True)

        st.markdown("**samples**")
        samples_info = pd.read_sql_query("PRAGMA table_info(samples)", conn)
        st.dataframe(samples_info, use_container_width=True, hide_index=True)

        conn.close()
        st.caption("Database loaded successfully.")
    except Exception as e:
        st.error(f"Failed to load database: {e}")
